const QuoteActionTypes = {
  SAVE_QUOTE_START: 'SAVE_QUOTE_START',
  SAVE_QUOTE_SUCCESS: 'SAVE_QUOTE_SUCCESS',
  SAVE_QUOTE_FAILURE: 'SAVE_QUOTE_FAILURE',
  UPLOAD_QUOTE_IMAGE_START: 'UPLOAD_QUOTE_IMAGE_START',
  UPLOAD_QUOTE_IMAGE_SUCCESS: 'UPLOAD_QUOTE_IMAGE_SUCCESS',
  UPLOAD_QUOTE_IMAGE_FAILURE: 'UPLOAD_QUOTE_IMAGE_FAILURE'
};

export default QuoteActionTypes;