const QuoteActionTypes = {
  SAVE_QUOTE_START: 'SAVE_QUOTE_START',
  SAVE_QUOTE_SUCCESS: 'SAVE_QUOTE_SUCCESS',
  SAVE_QUOTE_FAILURE: 'SAVE_QUOTE_FAILURE',
  SET_QUOTE_IMAGES: 'SET_QUOTE_IMAGES'
};

export default QuoteActionTypes;