sudo: required
language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
services:
  - docker

before_install:
  - docker build -t joydesigner/centrade-client -f Dockerfile.dev .

script:
  - docker run -e CI=true joydesigner/centrade-client npm run test
