const ProductActionTypes = {
  GET_CATEGORY_START: 'GET_CATEGORY_START',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
  GET_PRODUCTS_START: 'GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  GET_PRODUCTS_PAGE: 'GET_PRODUCTS_PAGE',
  GET_PRODUCTS_BY_PAGE: 'GET_PRODUCTS_BY_PAGE'
}

export default ProductActionTypes;