const SupplierActionTypes = {
  GET_SUPPLIER_START: "GET_SUPPLIER_START",
  GET_SUPPLIER_SUCCESS: "GET_SUPPLIER_SUCCESS",
  GET_SUPPLIER_FAILURE: "GET_SUPPLIER_FAILURE"
};

export default SupplierActionTypes;
